name: Static Analysis

on:
  push:
    branches:
      - main
      - '*.x'
  pull_request:
    branches:
      - main
      - '*.x'
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  static:
    name: Static Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        tools: composer:v2
        coverage: none

    - name: Install Dependencies
      run: composer update --prefer-stable --no-interaction --no-progress --ansi

    - name: Types
      run: composer test:types

    - name: Style
      run: composer test:lint
