name: Tests

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        php: ['7.4', '8.0']
        dependency-version: [prefer-lowest, prefer-stable]
        wp_version: ["latest"]
    env:
      CACHEDIR: /tmp/test-cache
      WP_CORE_DIR: /tmp/wordpress
      WP_VERSION: ${{ matrix.wp_version }}
    name: PHP ${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:v2
        coverage: none

    - name: Setup Problem Matches
      run: |
        echo "::add-matcher::${{ runner.tool_cache }}/php.json"
        echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Install PHP dependencies
      run: composer update --${{ matrix.dependency-version }} --no-interaction --no-progress --ansi

    - name: Install WordPress and Copy Project
      shell: bash
      run: |
        bash bin/install-wp-tests.sh wordpress_unit_tests root '' 127.0.0.1 $WP_VERSION

        # Go into the core directory and replace wp-content.
        rm -rf ${WP_CORE_DIR}/wp-content/plugins/pest-plugin-wordpress
        rsync -aWq --no-compress . ${WP_CORE_DIR}/wp-content/plugins/pest-plugin-wordpress

      - name: Unit Tests
        shell: bash
        run: |
          cd ${WP_CORE_DIR}/wp-content/plugins/pest-plugin-wordpress
          ./vendor/bin/pest --colors=always
