name: Tests

on: ['push', 'pull_request']

jobs:
  php-tests:
    strategy:
      matrix:
        php: [8.1, 8.2]
        wordpress: ["latest"]
    uses: alleyinteractive/.github/.github/workflows/php-tests.yml@main
    with:
      php: ${{ matrix.php }}
      wordpress: ${{ matrix.wordpress }}
